### ISSUE TITLE
Check for visitors's browser + OS; warn them if they cannot view variable fonts

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive-minisite#26]
A small minority of users report not seeing variable fonts on the page. This is for the simple reason that their OS doesn't yet support variable fonts:

![image](https://user-images.githubusercontent.com/45946693/69351781-d4c44580-0c49-11ea-9d89-3c3726d9b054.png)

_(From [a thread on Hacker News](https://news.ycombinator.com/item?id=21460419) on Wednesday, Nov 6])_

Ideally, we should detect this lack of support, and show users a message to let them know the site won't work well for them. Something like:

> It appears that you are visiting on an OS or web browser that doesn't yet support variable fonts.
> 
> While this isn't a problem on most sites using variable fonts (which just load static fonts as fallbacks), this specific website is showing a new variable font, so most of the diagrams do not work at all with static fonts. Please upgrade your browser or visit again on another browser or device. 
> 
> Thank you!

**Comment by RoelN** [comment]
It's possible to write a more thorough check, for example checking if a variable glyph is actually rendered. Much [like so](https://pixelambacht.nl/2013/font-face-render-check/). Before going that route, I'll ask around if there's another option to 100% verify variable font support.

**Comment by davelab6** [comment]
That method seems best to me.

Alternatively you could look at the user agent string in JS.... But that's
very complicated

**Comment by RoelN** [comment]
If free time permits I'm going to build a quick, 100% waterproof check a la [this](https://pixelambacht.nl/2013/font-face-render-check/). Until then, [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1600246) is the bug report for Firefox.

**Comment by arrowtype** [comment]
Woah, what a surprising method for testing this! 

But yeah, this is such a small portion of users (and presumably, a shrinking one), I wouldn't want it to be too much of a distraction from bigger issues.

**Comment by RoelN** [comment]
Agreed that this is such a minor issue, let's focus on other things!

**Comment by RoelN** [comment]
Closing this as the bug is on Firefox' side and they've got it on the radar
