### ISSUE TITLE
Add privacy policy

### ISSUE THREAD

**Issue by davelab6** [arrowtype/recursive-minisite#64]
Google Analytics TOS requires sites that intergrate with it to have a privacy policy :)

**Comment by arrowtype** [comment]
Thanks for flagging this, @davelab6!

This will presumably be an issue for any other Google Fonts-related minisites, as well. Is there a standard I can adopt for the Recursive minisite? I've searched a bit, but there is no clear & obvious answer to this.

![Screenshot: Google Analytics Privacy Disclosures Policy](https://user-images.githubusercontent.com/45946693/75642103-5a23a280-5c08-11ea-960f-08908b9af51c.png)

[Google Analytics Privacy Disclosures Policy](https://support.google.com/analytics/answer/7318509?hl=en)

Is it really as simple as adding something to the footer like:

> This site uses Google Analytics to collect usage data. For more information, see:
> [Google's Privacy & Terms](https://policies.google.com/technologies/partner-sites)

...or should it be more detailed?

**Comment by arrowtype** [comment]
Simple version added to site:

![image](https://user-images.githubusercontent.com/45946693/75643069-c2c04e80-5c0b-11ea-89a6-6ee107621440.png)

**Comment by davelab6** [comment]
Works for me
